### ISSUE TITLE
Problems on SDU install doc formatting and being out of date.

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/snapdrive-unix#10]
Page: [Connecting Linux hosts to storage systems](https://docs.netapp.com/us-en/snapdrive-unix/linux-installation-cmode/task_connecting_linux_host_to_the_storage_system.html)

Step 2 has the command on two lines and it needs to be a single line:
snapdrive config set vsadmin_name Vserver_name

While we are at it, add a note to Step 2:
Vserver_name should be the name of the SVM and should be mapped to the Vserver's management LIF IP address.

Also:
Step 1 should be removed.  No one is using 8.2.2 anymore.  If we want to keep the information then we need to put it as a note at the bottom of the page.

**Comment by ntap-bmegan** [comment]
@netapp-chandaj - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @NA-Scott - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-pavanrk

**Comment by netapp-pcarriga** [comment]
@NA-Scott Hi Scott,
Thank you for letting us know about this error in the documentation. We have corrected step 2 and updatedas you suggested:
https://docs.netapp.com/us-en/snapdrive-unix/linux-installation-cmode/task_connecting_linux_host_to_the_storage_system.html
