### ISSUE TITLE
Typo in the sidebar needs to be corrected.

### ISSUE THREAD

**Issue by netapp-pavanrk** [NetAppDocs/snapdrive-unix#6]
Page: [Installation and Setup Guide for Linux® for Clustered Data ONTAP](https://docs.netapp.com/us-en/snapdrive-unix/linux-installation-cmode/index.html)

Typo in the sidebar - Delete the extra "and".

![image](https://user-images.githubusercontent.com/70536826/111440025-f1806880-872b-11eb-8bc6-0eb5cdb61cc0.png)

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @netapp-pavanrk - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
