### ISSUE TITLE
No PDF download option

### ISSUE THREAD

**Issue by netapp-pavanrk** [NetAppDocs/snapdrive-unix#7]
Page: [SnapDrive for UNIX 5.3.2 Documentation](https://docs.netapp.com/us-en/snapdrive-unix/index.html)

I don't see an option to download PDFs on this repo. Do we need to enable this for "snapdrive-unix" repo?

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @netapp-pavanrk - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by ntap-bmegan** [comment]
This issue has been closed due to inactivity. Any interested party can comment to reopen the issue.
